[package]
name = "subxt"
version = "0.21.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "GPL-3.0"
readme = "../README.md"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Submit extrinsics (transactions) to a substrate node via RPC"
keywords = ["parity", "substrate", "blockchain"]

[features]
# Activate this to expose functionality only used for integration testing.
# The exposed functionality is subject to breaking changes at any point,
# and should not be relied upon.
integration-tests = []

[dependencies]
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
scale-info = { version = "2.0.0", features = ["bit-vec"] }
futures = "0.3.13"
hex = "0.4.3"
jsonrpsee = { version = "0.15.0", features = ["async-client", "client-ws-transport"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
tracing = "0.1.34"
parking_lot = "0.12.0"

subxt-macro = { version = "0.21.0", path = "../macro" }
subxt-metadata = { version = "0.21.0", path = "../metadata" }

sp-core = { version = "6.0.0", default-features = false  }
sp-runtime = "6.0.0"

frame-metadata = "15.0.0"
derivative = "2.2.0"

[dev-dependencies]
assert_matches = "1.5.0"
tokio = { version = "1.8", features = ["macros", "time"] }
